server {
    listen 80;
    server_name localhost;

    # Sirviendo los archivos estáticos generados por Vite
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # History API Fallback: reditige rutas al index.html para React Router
        try_files $uri $uri/ /index.html;
    }
}
